### ISSUE TITLE
failure on Interop Tag

### ISSUE THREAD

**Issue by GillesP227** [hMatoba/Piexif#66]
I have a failure on this image :

![2011-04-24-17-15-25 - croatie isabelle - img_2968](https://user-images.githubusercontent.com/43492324/46300154-4606ec00-c5a3-11e8-956e-b60242fc2c15.jpg)

The Interop section does not seem to be correct.
I use python 3.6.5.
No problem with exiftool : no Interop information.

Traceback (most recent call last):
[...]
    exif_dict = piexif.load(file)
  File "C:\Program Files\Python36\lib\site-packages\piexif\_load.py", line 48, in load
    exif_dict["Interop"] = exifReader.get_ifd_dict(pointer, "Interop")
  File "C:\Program Files\Python36\lib\site-packages\piexif\_load.py", line 119, in get_ifd_dict
    ifd_dict[tag] = self.convert_value(v_set)
  File "C:\Program Files\Python36\lib\site-packages\piexif\_load.py", line 243, in convert_value
    "tag: " + str(val[3]) + "\ntype: " + str(t))
ValueError: Exif might be wrong. Got incorrect value type to decode.
tag: 1
type: 0
>>>

**Comment by hMatoba** [comment]
Interop IFD is wrong in the file. ExitTool warns it, too.
http://exif.regex.info/exif.cgi
